// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsDzJYrNlwVL1H6OqDe_3HxrQnS_tJ3D4',
    appId: '1:583401891840:web:11f001d8152cb5dbf850e5',
    messagingSenderId: '583401891840',
    projectId: 'chat-heist',
    authDomain: 'chat-heist.firebaseapp.com',
    storageBucket: 'chat-heist.firebasestorage.app',
    measurementId: 'G-97ECCFBN5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIBvIIXN9GqQ_Rgpm27VgnOl6UzUXSeFk',
    appId: '1:583401891840:android:7e4bdda3b9c03e82f850e5',
    messagingSenderId: '583401891840',
    projectId: 'chat-heist',
    storageBucket: 'chat-heist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA2AgzZdJwUs8LShTzbYfrJ1H1wKSYEfQ',
    appId: '1:583401891840:ios:a792c4ba5cbdbe99f850e5',
    messagingSenderId: '583401891840',
    projectId: 'chat-heist',
    storageBucket: 'chat-heist.firebasestorage.app',
    iosClientId: '583401891840-lp92mqricrhj329hpn8k425u14lsk3hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA2AgzZdJwUs8LShTzbYfrJ1H1wKSYEfQ',
    appId: '1:583401891840:ios:a792c4ba5cbdbe99f850e5',
    messagingSenderId: '583401891840',
    projectId: 'chat-heist',
    storageBucket: 'chat-heist.firebasestorage.app',
    iosClientId: '583401891840-lp92mqricrhj329hpn8k425u14lsk3hp.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsDzJYrNlwVL1H6OqDe_3HxrQnS_tJ3D4',
    appId: '1:583401891840:web:96e0932e97d4f7e2f850e5',
    messagingSenderId: '583401891840',
    projectId: 'chat-heist',
    authDomain: 'chat-heist.firebaseapp.com',
    storageBucket: 'chat-heist.firebasestorage.app',
    measurementId: 'G-80B6CYCCGZ',
  );
}
